# Generated by Django 4.2.2 on 2023-06-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
    ]
