# Generated by Django 4.2.2 on 2023-06-23 09:20

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_employee_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=website.models.UniqueFileName('job_images/{uuid}_{filename}'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
