# Generated by Django 4.2.2 on 2023-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_vacancies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
