# Generated by Django 4.2.2 on 2023-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_job_job_vacancies_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_vacancies', models.JSONField(default=list)),
            ],
        ),
    ]
