# Generated by Django 4.2.2 on 2023-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_jobapplication_delete_nonjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_vacancies', models.JSONField(default=list)),
            ],
        ),
    ]
